# Generated by Django 2.2 on 2019-07-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='inactive', max_length=16)),
                ('question', models.CharField(max_length=200)),
                ('note', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('level', models.IntegerField(choices=[(1000, 'Easy'), (2000, 'Lower Intermediate'), (3000, 'Intermediate'), (4000, 'Upper Intermediate'), (5000, 'Difficult')], default=3000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
